core/urls.py
from django.contrib import admin
from django.urls import path, include

from main.views import front_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', front_page, name='frontpage'),
    path('main/', include('main.urls', namespace='main')),
]

main/urls.py
from main import views
from django.urls import path

app_name = 'main'
urlpatterns = [
   path('about/', views.about_page, name='about_page'),
]

main/models.py
from django.db import models

# Create your models here.

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User, related_name='userprofile', on_delete=models.CASCADE)
    def __str__(self) -> str:
        return self.user

main/views.py
from django.http import HttpRequest
from django.shortcuts import render

# Create your views here.

def front_page(request:HttpRequest):
    return render(request, 'main/frontpage.html', {'dados':'Hello friend'})

def about_page(request:HttpRequest):
    return render(request, 'main/aboutpage.html', {'dados':'Hello friend'})

userprofile/views.py
from django.shortcuts import render

# Create your views here.

main/templates/main/aboutpage.html
{% extends 'main/base.html' %}
{% block title %}
About Page
{% endblock title %}
{% block content %}
<h1 class="text-3xl font-bold underline">
About
</h1>
{% endblock content %}

main/templates/main/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>
    {% block title %}
    {% endblock title %}
  </title>
  
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class="max-w-4xl mx-auto py-4 px-6 flex items-center justify-between bg-teal-600">
        <div class="logo">
            <a href="/" class="text-white text-2xl">Home</a>
        </div>
        <div class="menu">
            <a href="{% url 'main:about_page' %}" class="text-white text-2xl">About</a>
        </div>
        <div class="menu">
            <a href="/" class="text-white text-2xl">Contact us</a>
        </div>
        <div class="menu">
            <a href="/" class="text-white text-2xl">Cart</a>
        </div>
    </nav>
    <div class="max-w-4xl mx-auto flex">
        {% block content %}
        
        {% endblock content %}
    </div>  
</body>
</html>

main/templates/main/frontpage.html
{% extends 'main/base.html' %}
{% block title %}
Front Page
{% endblock title %}
{% block content %}
<h1 class="text-3xl font-bold underline">
{{dados}}
</h1>
{% endblock content %}